### ISSUE TITLE
Supported character sets

### ISSUE THREAD

**Issue by pucilpet** [monoid-privacy/monoid#26]
Hello!
When trying to add a MYSQL database as a data silo, I get the following error message (open source version):

Error Connecting Silo
Something went wrong: Character set 'utf8' unsupported

This mysql database uses the following collation: utf8mb4_general_ci

What are the supported character sets? I would think that utf8 should be supported - it being so common. Or maybe there's something else wrong but the error message is being unhelpful?

**Comment by vigneshv59** [comment]
UTF8 should be supported, this seems like a bug in the connector -- what version of MySQL are you running? Also, I can help over slack if you're interested -- it might be quicker to debug!

**Comment by pucilpet** [comment]
mysql --version
mysql  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64)

I also tried the MariaDB connector but got the same error. I'll pop in @ Slack at some point. :)

**Comment by vigneshv59** [comment]
This should be fixed, there was an issue with the library we were working with MariaDB. You may have to pull the image for the updated loader to get the fix (you can just run `docker compose pull loader`)
